name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install netcat
      run: sudo apt-get install netcat
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
